name: diff-course
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - jupyterlab
  - huggingface_hub
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - scikit-learn
  - matplotlib
  - torchinfo
  - manim
